### ISSUE TITLE
Policy - Name Restriction 

### ISSUE THREAD

**Issue by beatrizpatricio7** [Azure/Community-Policy#4]
Hello,

I created a policy that restricts the name of the resources and resource groups. For example, all names must contain a certain parameter. But I wanted to add an exception, like "all names must contain a certain parameter or the name must be 'MonitorAgent'". But didn't work has expected. Is any other way to make this policy right?

This is the policy defenition that I tried:

{
  "mode": "Indexed",
  "policyRule": {
    "if": {
      "anyOf": [
        {
          "field": "name",
          "notContains": "MicrosoftMonitoringAgent"
        },
        {
          "not": {
            "field": "name",
            "contains": "[parameters('namePattern')]"
          }
        }
      ]
    },
    "then": {
      "effect": "deny"
    }
  },
  "parameters": {
    "namePattern": {
      "type": "String",
      "metadata": {
        "displayName": "namePattern",
        "description": "Pattern to use for names. Can include ? for letters and # for numbers."
      }
    }
  }
}

**Comment by kenieva** [comment]
Hey, I would recommend using our new [Modify ](https://docs.microsoft.com/en-us/azure/governance/policy/concepts/effects#modify) effect on Tags. You should be able to have it so that it checks the tag value and if its not then add a tag with that value or if the tag exist but doesn't have the correct value replace the tag to whatever value you want. 

Here are some examples: https://github.com/Azure/azure-policy/tree/master/samples/Tags
